.gitignore, infoblox_client/tests/unit/test_object_manager.py
Modified .gitignore to skip temporary Vim files
=> Fix unit test `delete_object_by_ref`

infoblox_client/object_manager.py, infoblox_client/tests/unit/test_object_manager.py
DNSZone returned None independently from success or fail
of create request.
Updated code to return DNSZone object on successfull zone creation.
Closes #5.
=> Return DNSZone object in create_dns_zone

infoblox_client/objects.py
Added support for 'allowed_object_types' attribute for Extensible
Attribute Definition.
=> Add allowed_object_types field for EA Definition

infoblox_client/connector.py, infoblox_client/feature.py, infoblox_client/tests/unit/test_feature.py
Added Feature class that is used to determine Infoblox features
supported by a WAPI version.
Please comment:
I am not sure that FEATURE_VERSIONS belong to infoblox-client. The code is cleaner as it is.
But I feel like FEATURE_VERSIONS should belong to networking-infoblox constants.py.
Recommendations please.
=> Add utility to determine supported feature

infoblox_client/objects.py
HostRecord objects had mapping 'ip' to 'ipv4addrs' or 'ipv4addrs'.
But this field contains list of ips, so adding 'ips' mapping to the same
fields.
For backward compatibility reasons 'ip' to 'ipv4addrs' or 'ipv4addrs' is
still in place.
=> Add 'ips' alias for HostRecords ip field

infoblox_client/objects.py, infoblox_client/tests/unit/test_objects.py
If response contains string values 'True' or 'False', it is converted
into appropriate booleans.
Removed check 'if value' in to_dict method, since now False is also
valid value that has to be passed in WAPI request.
=> Convert EA values from response into booleans

infoblox_client/objects.py, infoblox_client/tests/unit/test_objects.py
'host' field is not writtable in IP object, but it was send to NIOS
on adding new ip to existent HostRecord.
To prevent sending 'host' field to NIOS it was moved to _shadow_fields.
So it exists in object, but not send on via API on object updates.
Closes: #18
=> Prevent sending host field on IP update

infoblox_client/object_manager.py
Currently if object already deleted on NIOS side,
delete operation fails preventing object deletion from Neutron.
Updated code to do not fail if object is already deleted.
=> Do not fail if object is not found on delete

infoblox_client/connector.py, infoblox_client/tests/unit/test_connector.py
If 'ssl_verify' is set to False, then each api request generates ssl
warnings.
Added new option for connector to be able to disable these warnings.
By default this option is turned off.
This option is not expected to be used in production, as well as
'ssl_verify' = False, so make sure 'silent_ssl_warnings' usage is
limited with development/test environments.
Note: warnings are disabled on urllib3 level, so it affects all
instanses of requests as a result. Use with option cautiously.
Closes: #22
=> Add 'silent_ssl_warnings' option to connector

infoblox_client/connector.py, infoblox_client/tests/unit/test_connector.py
Previously if NIOS reply was not in json format ValueError was raised from
json library, and reply itself was not logged.
Typically if reply is not in json format it indicates some error response.
Updated reply parsing to raise an exception with reply details
if reply is not json format.
Closes: #25
=> Raise exception with details if reply is not json

infoblox_client/object_manager.py, infoblox_client/tests/unit/test_object_manager.py
Searching IPRange before creating suffers from synchronization delay
in GM+CPM environment [1].
But if search step is ommitted create IPRange request is proxified to
correct CPM member.
Updated object_manager to do not check for IPRange existence before
creating it.
[1] https://jira.inca.infoblox.com/browse/OPENSTACK-724
=> Do not search IPRange before creating

infoblox_client/objects.py, infoblox_client/tests/unit/test_objects.py
IP version detection worked incorrectly if address is passes in
'network' field.
But worked fine if 'cidr' field is used.
Added 'network' field to list of fields that are used to detect needed
class version.
Closes: #30
=> Add 'network' field to ip versioned fields

infoblox_client/object_manager.py
NIOS does not allow to set DHCP options for IPv6 over WAPI on network
creation and raises:
IBDataConflictError: IB.Data.Conflict:Set the option DHCP.routers from
the General Properties section.
So skipping setting DHCP options for IPv6.
Reported issue to NIOS: "Unable to create IPv6 network over WAPI if 'routers' is in options"
https://jira.inca.infoblox.com/browse/WEBAPI-543
=> Skip adding DHCP options for IPv6

README.rst, infoblox_client/connector.py
Added logging of each API call in connector with debug log level.
Reuses neutron logger from neutron if executed in neutron context.
Known limitations:
Infoblox-client is external package for neutron, so debug messages from
this package are not included in default neutron logger output even if
it is set to debug log level.
Closes: #24
=> Log all api calls in connector on debug level

infoblox_client/object_manager.py, infoblox_client/tests/unit/test_object_manager.py
Network_exists method was quite ineffective way of checking network
existence. It does not return network, so if any action has to
be performed on network then new API call has to be done to get network.
Using get_network instead is more effective, it returns None is no
network was found, or Network object if it exists.
Also get_network was updated to do not throw exception if no network is
found, so just None is returned.
Closes: #37
=> Remove network_exists and change get_network

infoblox_client/objects.py, infoblox_client/tests/unit/test_objects.py
EAs with empty values must not be sent to Infoblox.
=> Check for empty values in EA

infoblox_client/object_manager.py, infoblox_client/tests/unit/test_object_manager.py
NIOS Cloud Platform Member does not allow to search records using
'ipv4address'/'ipv6address' NIOS type.
To be able to delete all associated records another approch is selected.
Now each supported for delete object type is checked separately:
- 'record:a'
- 'record:aaaa'
- 'record:ptr'
- 'record:txt'
- 'record:cname'
To remove first three types unbind_name_from_record_a was reused.
'record:txt' and 'record:cname' do not have ip field in it,
so can not be searched directly. Added
delete_objects_associated_with_a_record to delete related records.
delete_all_associated_objects is now deprecated and
unbind_name_from_record_a should be used instead.
Closes: #46
=> Rework delete_all_associated_objects logic

infoblox_client/connector.py, infoblox_client/tests/unit/test_connector.py
Connector crashes when WAPI returns error message.
Response is a dict, so 'text' field was incorrectly accessed
and caused crash.
Corrected accessing 'text' field in response.
Added UT to validate that correct exception is raised.
Closes: #47
=> Fix error handling in create_object

infoblox_client/object_manager.py
Removed try-except block from create_dns_zone to allow capture
exception on upper level.
Previous behavior:
If dns zone creation fails exception is raised on object level,
then create_dns_zone catch this exception and just log error message
without reraising exception.
So caller is not aware about success status of zone creation.
New behavior:
Exceptions are no longer caught on create_dns_zone level,
and can be caught on create_dns_zone caller level.
Closes: #48
=> Do not catch exception on create_dns_zone level

infoblox_client/objects.py, infoblox_client/tests/unit/test_objects.py
Old way of getting ip version for ib_objects is accessing privite
variable _ip_version.
Adding ip_version as part of public interface.
Includes UT to validate field is returned correctly.
Closes: #56
=> Add ip_version as a public property

infoblox_client/connector.py, infoblox_client/object_manager.py, infoblox_client/tests/unit/test_connector.py
Raising ib_ex.InfobloxSearchError exception was replaced with returning
None if NIOS replied with non-ok code.
Updated object_manager methods accordingly to remove exception handling,
since this exception is no longer raised.
Added UT to validate that None is returned if non-ok code is returned.
Closes: #57
=> Return None instead of exception if search failed 

infoblox_client/object_manager.py
Previously domain-name-servers option generation was turned off for ipv6
with other dhcp options ('routers' and 'dhcp-server-identifier').
Using this options caused failures for ipv6 on network creation.
But deeper investigation shows that 'domain-name-servers' is a valid
option for ipv6, so enabling it.
Closes: #64
=> Allow domain-name-servers for ipv6

infoblox_client/object_manager.py, infoblox_client/objects.py, tests/test_object_manager.py, tests/test_objects.py
EAs generated on network update replaced all existent EAs for network,
even user defined.
Updated workflow to merge existent network EAs with newly generated EAs.
Newly generated EAs have higher priority over existen EAs.
Added ea_dict property to EA object interface to be able to retrieve internal
representation of eas in {ea_name: ea_value} format.
Closes: #63
=> Update existent EA for network instead of replace

infoblox_client/connector.py, infoblox_client/objects.py, infoblox_client/utils.py, tests/test_utils.py
ssl_verify for Connector was passed to requests.Session.verify without
changes. ssl_verify can be boolean or string.
If it is a string it was excected to contain path to certificate.
To simplify using ssl_verify option now it can be passed in as string,
that containg 'True' or 'False'. In this case string would be converted
to boolean and passed into requests.
All other values are passed as is, i.e. booleans are passed unchanged,
as well as any string that is not equals to 'True' or 'False'.
Converting value to bool was moved from objects into utils,
because now used from connector as well.
Closes: #65
=> Convert strings into booleans for ssl_verify

infoblox_client/objects.py
'start_addr', 'end_addr' fiels from IPRange were not taken into account
on detecting IP version of object.
Added them to the list of fields that can contain ip versioned object.
Closes: #77
=> Add 'start_addr', 'end_addr' to ip detection list

infoblox_client/object_manager.py, tests/test_object_manager.py
create_required_ea_definitions return list of EA Definitions
that were missing and were therefore created.
This list is used for reporting purpose.
=> create_required_ea_definitions return created list

infoblox_client/objects.py, tests/test_objects.py
Previously processing rule was applied to value directly,
so list values were converted to stings as a result.
Currently if value of EA is list of tuple, then processing rule would be
applied on per element basis.
Closes: #84
=> Add support for list and tuple values to EA object

infoblox_client/objects.py
Extensible attributes are not returned by default for NetworkView
object. To be able to merge old EAs with new EAs, 'extattrs' field
should present in return fields.
Updated NetworkView model to explicetely request 'extattrs' via return
fields.
Closes: #89
=> Add return_fields to NetworkView

infoblox_client/objects.py
_return_fields was not set for DNSZone/DNSView, so 'extattrs' were not
returned from NIOS for these objects.
Added _return_fields with 'extattrs' and other needed fields.
Closes: #92
=> Add 'extattrs' to DNSZone/DNSView return_fields

infoblox_client/object_manager.py, infoblox_client/objects.py, tests/test_object_manager.py
'configure_for_dns' can be set to False to create host record without
dns zones.
Added this field to HostRecordV4 and HostRecordV6 objects.
Updated create_host_record_for_given_ip and
create_host_record_from_range to optionally accept 'use_dns' flag,
which is True by default.
Having 'use_dns' as an optional flag does not brake backward
compatibility with older versions.
Closes: #94
=> Add 'configure_for_dns' field for HostRecord

infoblox_client/connector.py, infoblox_client/objects.py, tests/test_connector.py, tests/test_object_manager.py, tests/test_objects.py
max_results option is translated into '_max_results' WAPI option:
Maximum number of objects to be returned. If set to a negative
number the appliance will return an error when the number of returned
objects would exceed the setting. The default is -1000. If this is set
to a positive number, the results will be truncated when necessary.
This option is available for get_object method in connector and
for search and search_all methods for objects that are inherited from
InfobloxObject.
Closes: #62
=> Add max_results option to connector and objects

tests/test_connector.py
wapi_version requires values in '\d+\.\d+' format for a while, i.e.
it should not start with 'v', so '2.2' is a valid wapi version, but
'v2.2' is not.
Cleaned up invalid versions from tests.
=> Remove 'v' from wapi version in tests

infoblox_client/objects.py, tests/test_objects.py
Tenant refers to 'grid:cloudapi:tenant' NIOS type and is intended to be
used to update tenant name on NIOS side.
Closes: #96
=> Add Tenant object

tests/test_objects.py
Adding tenant review had UT in it, and merging add max_results
option broke that UT.
Fixing UT to include max_results in expected parameter for get_object
call.
=> Fix test failure after conflicting changes

infoblox_client/connector.py, tests/test_connector.py
'max_results' defines maximum number of objects to be returned.
If set to a negative number the appliance will return an error
when the number of returned objects would exceed the setting.
The default is -1000. If this is set to a positive number,
the results will be truncated when necessary.
'max_results' was option for get_object method for a while.
Adding it as connector option to set it once and globally.
If 'max_results' defined as connector option, then it applied to
all get_object calls.
'max_results' value can be redefined for particular get_object calls
by passing another 'max_results' value to get_object.
Closes: #101
=> Add 'max_results' as connector option

infoblox_client/connector.py, tests/test_connector.py
Passes max_retries option to requests adapters. Default value is 3.
The maximum number of retries each connection should attempt. Note, this
applies only to failed DNS lookups, socket connections and connection
timeouts, never to requests where data has made it to the server. By
default, Requests does not retry failed connections. If you need
granular control over the conditions under which we retry a request,
import urllib3's Retry class and pass that instead.
More info about max_retries can be found in requests documentation [1].
[1]
http://docs.python-requests.org/en/master/api/#requests.adapters.HTTPAdapter
Closes: #104
=> Add max_retries option to connector

infoblox_client/connector.py
Previously failure on get was logged with debug log level, so error
itself was not seen fby user.
Changed log level for search failures to 'error', so all this error are
logged.
Closes: #107
=> Log failure on get with Error log level

infoblox_client/objects.py
Within wapi 2.2+ list of default fields for member object was expanded.
Added support for next fields:
- platform
- config_addr_type
- service_type_configuration
Closes: #118
=> Add default fields for Member

infoblox_client/objects.py, tests/test_objects.py
Previous behavior was to raise an exception on receiving unknown field.
It caused issues when NIOS replied with some unknown yet field.
Currently If unknown field is received it is ignored, and no exception
is raised.
=> Do not fail on processing unknown fields

infoblox_client/objects.py
Previously if reply is received from NIOS update was forced to
update only dict and skip other fields. In case of only_ref is False
it was inccorect behavior.
Updated code to pass value of only_ref down to update_from_dict.
=> Pass only_ref option to update_from_dict

infoblox_client/object_manager.py, infoblox_client/objects.py, tests/test_object_manager.py, tests/test_objects.py
Networking-infoblox need to search non-DNS hosts using network view
instead of dns view(non-DNS host root dns views has same name for all
networks views except default)
So add network view support to host and corresponding object_manager
functions.
=> Add network_view support for host records

infoblox_client/object_manager.py, infoblox_client/objects.py, tests/test_object_manager.py
Networknig infoblox need to update DNS zone extensible attributes when
network changes, so add extensible attributes update support for DNSZone
object.
=> add zones extensible attribute update support

infoblox_client/objects.py, tests/test_object_manager.py
I was having timeout issues searching by ipv4addr.  I've noticed in my environment, searching by ptrdname is much faster.
=> Add ptrdname search option to PtrRecord objects

infoblox_client/object_manager.py, tests/test_object_manager.py
If port creation failed after ip allocation - allocated address
does not removed, so next attempt to create port with same MAC failed.
This fix search fixed addresses with given MAC and if exists fixed
address from given range - use this address instead allocation new one.
Closes-Bug: 1628517
=> Fix IP allocator to reuse IP with same MAC/Range

infoblox_client/object_manager.py, infoblox_client/objects.py, tests/test_object_manager.py
Networking-infoblox need ability to search HostRecords by MAC address.
Thi fix added code to support search HostRecords by MAC.
=> Add search HostRecords by MAC

README.rst, infoblox_client/objects.py
Here's to add support for CNAME objects. I had a hard time working out the interactions between the three search/update field lists but I think I got to the bottom if it and structured it appropriately. 
I also tried to update the comments under the base infoblox object to reflect the changed in PR #140 but, again, may or may not have the right understanding of it.
I don't think this requires new tests since it's not adding any helper functions, and earlier PRs for additional object support don't add new tests. But I'm happy to try adding some more if you'd prefer!
=> Adding record:cname support.

infoblox_client/objects.py
I'm trying to use SRVRecord objects and am seeing `objects.SRVRecord.create` return different fields depending on if the object exists or not.
If the SRVRecord does exist, `create` fetches the object and returns the fields `_ref, name, target, priority, weight, port, view`.
If the SRVRecord doesn't exist, `create` creates the object, parses the reply with `_object_from_reply` and returns just `_ref`.
For my purposes I'd like `create` to return at least `name, port, priority, weight, target` regardless of if the record already exists. I think the right way to do that is by specifying these in `_return_fields`, and I thought it wouldn't hurt to have `view` there too.
Thanks for any feedback you can offer, and happy holidays!
=> Add _return_fields to SRVRecord

infoblox_client/objects.py
Perhaps I am misunderstanding `_return_fields` as I would expect the list to be larger. For example most Class's do not have comment in there.
=> Add comment to Network Class

HISTORY.rst, infoblox_client/__init__.py, setup.py
By mistake i deleted pypi version 0.4.16 and we cannot reuse removed version so creating new patch with bumped version 0.4.17
=> Bump version to 0.4.17

infoblox_client/connector.py, tests/test_connector.py
WAPI 1.4 is extremely old. I would like to update this default to 2.1 which was released with NIOS 7.1 in April 2015. 7.1 is the oldest version still in end-of-life supportability. There is no reason to keep it on 1.4 which was released with NIOS 6.8. We just need to ensure this doesn't break any other plugins that rely on this module such as OpenStack and Ansible (it definitely won't break the Ansible modules).
=> Default WAPI version update

infoblox_client/connector.py, requirements.txt
Python 2.7.5, RHEL 7.4, requests 2.18.4. Ran into this while trying to use the `nios_*` family of modules in Ansible 2.5.
=> Requests no longer vendors urllib3

.travis.yml, infoblox_client/connector.py, setup.py, tests/test_connector.py, tox.ini
undo change from 3c5629e519f82b501d545d54099d7087124704eb
From my testing with python-3.6, disabling SSL Verification on the session still attempts to verify certificates.
=> Disable SSL Verification in Request Options

infoblox_client/objects.py
When an object is created the return fields does not
return the IP address.
In the case you use the func:nextavailableip help function
it enforce to do a lookup of the current retrieved _ref
to retrieve the newly created IP.
Using _fields as _return_fields fix this issue.
=> Return IP address after ARecords creation

infoblox_client/connector.py
Fix a regexp presented as a string.
tox -e pep8 now runs as attended.
=> Fix a code coverage issue with pep8

infoblox_client/feature.py
wapi version above 2.9.Examle :2.10.
previously we were using string.digits which was taking value between "0-9".
so when a value of "10" or above was entered we were getting error
@adsri please review
=> This commit contains changes that takes care when user enters a

AUTHORS.rst, README.rst, infoblox_client/connector.py, tests/test_connector.py
We have created functionality to search in Infoblox, and in addition to default fields, we would like to have extendable attributes on all elements. This is done by adding a `+` sign after `_return_fields` in WAPI, but is to my knowledge not possible in Infoblox-Client. 
This change enables users to get both the default fields AND the specified extra fields. This reflects how the WAPI works.
Example code to get default fields + extra return_fields below:
```py
def search_extensible_attribute(connection, place_to_check: str, extensible_attribute: str, value: str):
"""
Find extendible attributes. Async method
:param connection: Infoblox connection
:param place_to_check: Can be `network`, `networkcontainer` or `record:host` and so on.
:param extensible_attribute: Which extensible attribute …
```
=> Added possibility for a 'default' flag in return fields, reflecting WAPI

AUTHORS.rst, infoblox_client/objects.py, tests/test_objects.py
Thank you make this useful library! Please let me enhance a feature for DNS.
Current implementation couldn't touch with `aliases` field of HOST record for DNS.
This patch enables to get/set it.
=> Changed to able to get/update 'aliases' parameter of HOST record for DNS

infoblox_client/connector.py, tests/test_connector.py
After first login to the API, a session cookie is generated, which can be re-used for every subsequent request, avoiding the need to re-authenticate.
There is an added lag during connector initialization, because that's when the cookie is established, however all subsequent calls are much faster than before.
The use-case which required this change is an environment where authentication to Infoblox uses timed 2FA (two-factor authentication), so the passwords are not static. After a given amount of requests with the same 2FA code, the underlying authentication mechanism starts denying login, causing any subsequent calls to fail. Using the cookie guarantees that the session will remain valid for as long as the value defined for session timeout (same as the web UI session timeout, defined on …
=> Use ibapauth cookies for the entire session

infoblox_client/objects.py
Hi all,
Adding some useful fields to the IPRange object for DHCP ranges.
IPRange
-> template
-> comment
-> server_association_type
-> failover_association
I have tested these on create and search methods, and they appear to work. They don't work on update, but that seems to be a broader issue that I'll open a bug for.
=> Dhcp range add some useful fields

infoblox_client/objects.py
Network
-> zone_assiociations
IPRange
-> server_association_type
-> failover_association
One use case it to map IPRange to failover cluster with:
server_association_type='FAILOVER'
failover_association='YOUR_FAILOVER_CLUSTER_NAME'
=> Add a few fields useful for DHCP Network and Range creation

infoblox_client/objects.py, tests/test_objects.py
This patch tries to follow the current implement scheme
for IP creation with IPAllocation object as an IP.
(As documented in the README.rst)
As ip / ipvXaddr could be an IPallocation object this patch
defines a getter/setter on ipvXaddr to ensure IPAllocation
is converted to string
=> Allow IPAllocation to be used as ip for ARecord creation

README.rst, infoblox_client/objects.py, tests/test_objects.py
New PR due to some messed up rebasing.
Added `ms_server` fields to `FixedAddress`, enabling us to reserve an address on our MS server.
Docs:
```
ms_server¶
The Microsoft server associated with this fixed address.
Type
A/An MS DHCP server struct.
Create
The default value is empty.
Search
The field is available for search via
‘=’ (exact equality)
```
Changed tests to include checking this.
Added a tiny doc to have an example on to pass the struct properly.
=> Added `ms_server` fields to `FixedAddress`

infoblox_client/exceptions.py
This enables us to actually do logic on the exceptions kwargs raised without parsing the string.
With this MR one could do:
```py
try:
FixedAddressV4.create_check_exists(connector=connection,
ip='192.168.0.2',
mac='aa:bb:cc:dd:ee:ff')
except BaseExc as error:
if error.kwargs.get('code') == 400:
... logic
```
Current implementation forces us to do something like this, which is very annoying:
```py
try: 
FixedAddressV4.create_check_exists(connector=connection,
ip='192.168.0.2',
mac='aa:bb:cc:dd:ee:ff')
except BaseExc as error:
match = re.search(r'\[code ([0-9]+)\]$', str(error), re.I)
status_code = int(match.group(1))
if status_code == 400:
... logic
```
It's important to note that just catching the exception and how it behaves has not changed.
=> Added kwargs to the BaseExc.

infoblox_client/connector.py, infoblox_client/objects.py, tests/test_connector.py, tests/test_objects.py
Reverts infobloxopen/infoblox-client#238
This entire logic needs to be rethinked and redone. It's currently messing up almost all (if not all) `get_object` functions. Every object that does not have `ipv4addr` in it, will now get an extra field with `ipv4addr` appended to it. The code/logic behind the `ipv4addr` extraction also only works where the IP is mirrored in the ref - which basically only happens for PTR records. Obviously this will break on multiple scenarios, including any IPv6.
In practice this means if you do fetch for `network` objects with `get_object` like this:
```py
args = ['network',{'comment~:': '^(mycomment)'}]
kwargs = {
'return_fields': [
'comment',
'network',
]
}
response = connection.get_object(*args, **kwargs)
print(response)
```
you'll get the response from …
=> Revert "#195: Queried PTR Records don't have an IP"

requirements.txt
This package currently requires `six` version `1.13.0` some third party packages require `1.14.0` or higher,  which can create conflicts in projects. 
I've looked into the changelog, and there doesn't seem to be any breaking changes that would affect this package. 
`six` version `1.14.0` removes support for Python `2.6` and `3.2`, seeing as Python 2 in its entirety is EOL and `3.2` has been EOL since 2015, I don't see this being a problem.
=> Update six package

infoblox_client/objects.py
We current tree, using IPAllocation breaks at oslo json
serialisation.
Using the same principle used in IP Class, Arecord and AAAArecord
get an attribute getter/setter to "stringify" IPallocation Objects.
=> Allow IPAllocation on Arecord and AAAArecord creation

infoblox_client/objects.py
Issue:
When calling objects.NetworkContainer.from_dict(args)
the _custom_field_processing functions are not called
For example you get a list of dict for options instead of
list of Dhcpoption objects
This applies for all Objects that are subclass with V4 and V6
Root Cause:
from_dict NetworkContainer class methodis from InfobloxObject from_dict
classmethod
This parent class method from_dict is using the NetworkContainer class
attibutes (And there is none)
We definitly need to lookup the V4 or V6 subclass first to get
the class & attributes right
=> Fix a nasty bug when calling abstracted class from_dict with V4 & V6 subclass

infoblox_client/connector.py, tests/test_connector.py
* Client user was unable to distinguish 4xx from 5xx errors returned by the WAPI.
* If API returns 4xx or 5xx error, Connector's _get_object method will raise an exception.
* If _get_object is called by public get_object method, the last one will
catch above exception and try to repeat the request with option
"_proxy_search=GM".
* Closes #290.
* `test__get_object_raises_search_error` -- checks if `_get_object` method will raise exception, when WAPI response mock will have `404` status code.
* `test_get_object_without_proxy_flag` -- updated test mock for `_get_object` method to raise `HTTPError` instead of returning `None`.
@anagha-infoblox
=> Updated Connector's method to raise exception if API response status is incorrect

infoblox_client/objects.py, tests/test_objects.py
* Paging on calls like Arecord.search_all() are broken, because the paging parameter are dropped in this function
This patch passes it through
* Added paging=False argument in the function call.
* Unit tests are performed.
=> PR: Objects pass through the paging argument

.github/workflows/test.yml, infoblox_client/objects.py, infoblox_client/utils.py, tests/test_object_manager.py
* Some `infoblox-client` unit tests were broken by previous changes.
* Related to PR #307.
* We need a CI unit testing pipeline to check if some change brakes the `infoblox-cleint` logic.
* Created Github actions piplines for testing/linting.
* Fixed a couple of mintor tests related to `get_object`'s `paging` parameter in `test_objects.py` module.
* `test_object_manager/test_delete_host_record_deletes_host_record_object` -- fixed mock assertion.
* `test_object_manager/test_get_network_gets_network_object` -- fixed mock assertion.
* `test_object_manager/test_delete_ip_range_deletes_infoblox_object` -- fixed mock assertion.
* `test_object_manager/test_delete_network_deletes_infoblox_network` -- fixed mock assertion.
* `test_object_manager/test_delete_network_view_deletes_infoblox_object` -- …
=> Created GH actions pipeline for unit-testing/linting

infoblox_client/objects.py, tests/test_objects.py
* The update calls from the Infoblox-client plugin  for object 'record:aaaa' on fields ['name', 'ipv6addr'] are breaking as per bug NIOS-84322
* Added ['ipv6addr', 'name'] to DNSZone class update fields.
* Fixed Test cases to support the update call.
* No Tests
=> Changes as per bug/NIOS_84322

e2e_tests/connector_facade.py, e2e_tests/test_objects.py, infoblox_client/objects.py
* Previously, `create` method returned `response` as an object field only when object already exists. For other cases `response` field wasn't returned, because it was dropped by [to_dict method](https://github.com/infobloxopen/infoblox-client/blob/v0.5.0/infoblox_client/objects.py#L268-L283), which deserializes API response into a python class instance.
* Now `create_check_exists` method will return WAPI `response` as a field of returned object for each case (e.g. create a new object, update existing object, just find existing object), because this `response` field is added after object deserialization.
* Also added docstring for the `create` method.
*  Added update_object method for the e2e connector_facade.py. Now, when e2e connector facade is used to update some object, facade will …
=> Bug NIOS-84387: Fixed response field return logic for the InfobloxObject.create method

infoblox_client/exceptions.py, infoblox_client/objects.py, tests/test_objects.py
* Invalid result while searching with Non-searchable fields
* Added functionality to check if the field is present in searchable fields else will raise an exception.
=> [NIOS-84390] Client should throw error, when serching with non-searchable fields

README.rst, e2e_tests/test_objects.py, infoblox_client/objects.py
* This allows EAs to be inherited from the parent object instead of
being overridden when calling objects.HostRecord.create()
* allow use_for_ea_inheritance field in IP objects
* Tested with WAPI version 2.11.3
=> Allow use_for_ea_inheritance field in IP objects

.github/pull_request_template.md, .github/workflows/test.yml, tests/test_connector.py, tox.ini
* Python 3.6 has reached EoL and no longer supported by ubuntu-latest runner.
* For matrix test with tox, changed Ubuntu version to 20.04, since matrix test still needs a python versions <= 3.6.
* For lint and sphinx jobs, updated python version to 3.8.
* See https://github.com/actions/setup-python/issues/544#issuecomment-1332535877
=> Fixed python version incompatibility in GH workflow

.github/workflows/test.yml, infoblox_client/connector.py, infoblox_client/utils.py, tests/test_connector.py
This pull request includes several improvements and fixes related to cookie handling and authentication processes:
- Cookie Validation and Retry Mechanism: Implemented validation for cookies and added a retry mechanism for handling HTTP 401 error codes.
- Updated Cookie Handling: Enhanced cookie management using CookieJar for test cases to ensure better handling and storage of cookies.
- Removed Python 3.5 Support: Dropped support for Python 3.5 from the GitHub workflow to streamline the codebase and focus on more recent versions.
- Linting Fixes: Addressed various linting issues to improve code quality and maintainability.
- Additional Logging: Added more detailed logs for authentication processes and JSON response parsing to aid in debugging and monitoring.
- Re-authentication …
=> [IMP] Cookie Validation and Retry Mechanism on 401 Error

.readthedocs.yaml, HISTORY.rst, README.rst, docs/Makefile, infoblox_client/__init__.py, setup.py
- Added YML config file for ReadTheDoc
- Enhancement of debug logs and exception messages
=> Release notes for v0.6.2
