infoblox_client/objects.py, infoblox_client/tests/unit/test_object_manager.py, infoblox_client/tests/unit/test_objects.py
Introduces Extensible Attributes sub objects for NIOS objects.
Auto build EA object from NIOS reply if it has 'extattrs' field.
=> Add Extensible Attributes support

infoblox_client/object_manager.py, infoblox_client/objects.py, infoblox_client/tests/unit/test_object_manager.py
…Manager.
Please bump version after it's merged.
=> Add Extensible Attribute Definition support 

README.rst
Describes usage of objects public methods:
- create
- search
- search_all
- update
- delete
=> Update README.rst with objects interface

infoblox_client/objects.py
Added capability to set EA values on Member object.
Also allowing searching for Member using it's ip address.
=> Set Extensible Attributes values on Member object

infoblox_client/feature.py
Feature version for member_ipv6_setting was previously
set incorrectly.
=> Update feature version for member_ipv6_setting

infoblox_client/objects.py, infoblox_client/tests/unit/test_objects.py
If object already exist on NIOS side during create stage,
then it was fetched from NIOS to get reference to it.
During the fetch operation infoblox-client object fields were updated
with values obtained from NIOS side, as a result original values were
overriten and update_if_exist flag worked incorrectly.
Introduced 'only_ref' flag for fetch to limit object updating with
reference and prevent overriding other fields.
Closes: #45
=> Fix updating object from create method

infoblox_client/objects.py
Allow searching of FixedAddress using network cidr.
=> Add 'network' to search fields of FixedAddress

infoblox_client/objects.py
Allow searching of Host Record using dns zone.
=> Add 'zone' to search fields of Host Record

infoblox_client/utils.py, tests/test_connector.py, tests/test_utils.py
=> Flake8 fixes

infoblox_client/objects.py
_value_to_bool method was replaced with try_value_to_bool from utils
module, so removing dead code.
=> Remove dead code (_value_to_bool)

infoblox_client/objects.py
Add the ability to fetch the DHCP options associated to a FixedAddressV4
=> Add _build_options() to FixedAddressV4

infoblox_client/object_manager.py, tests/test_object_manager.py
Previously create_ea_definition always catched InfobloxCannotCreateObject
exception from connector. As a result upper level could not identify if
failure occured or not.
Added optional parameter 'reraise' to create_ea_definition and
create_required_ea_definitions to reraise InfobloxCannotCreateObject
error.
By default reraise is set to False, so old behavior is preserved
and failure on object creation is just logged without exception.
If reraise is set to True, error is logged and exception is reraised.
=> Allow raising exception in create_ea_definition

infoblox_client/__init__.py, setup.py
Please also tag this version to 0.4.9
=> Bump version to 0.4.9

HISTORY.rst, docs/conf.py, infoblox_client/__init__.py, setup.py
=> Bump version to 0.4.10

infoblox_client/objects.py
=> implement SRVRecord object

HISTORY.rst, infoblox_client/__init__.py, setup.py
Just a version bump. Please let me know if there's anything to add.
=> Bump version to 0.4.13

infoblox_client/connector.py, tests/test_connector.py
=> Fix for #152

README.rst
Some markup changes for readability, and a new example.
=> Markup improvements & new example

infoblox_client/objects.py
As suggested in https://github.com/infobloxopen/infoblox-client/issues/155.
=> Add comment field to some objects

infoblox_client/connector.py
=> Allow passing delete arguments when deleting an object

setup.py
Makes ``make test`` & coverage work again
=> Fix test_suite location.

setup.py
As we now build with python36 in the CI line (See tox.ini).
=> Update setup.py classifier with python36

infoblox_client/objects.py
Hello,
This small change is to allow setting the comment field on record creation
=> Allow to set comment on A and AAAA record creation

infoblox_client/objects.py
addressing issues  #221 and #193
=> Adding name filed for Fixed Address and ttl fields for some records

.travis.yml, infoblox_client/objects.py, tests/test_objects.py
=> Fixing update IP option for A Record

infoblox_client/objects.py, tests/test_objects.py
Added UTs along with MX record.
=> Added MX Record

README.rst
MXRecord support mentioned in ReadMe
=> Readme Updated

infoblox_client/connector.py, infoblox_client/exceptions.py, infoblox_client/feature.py, infoblox_client/objects.py, infoblox_client/utils.py, requirements.txt, tests/test_connector.py, tests/test_feature.py, tests/test_object_manager.py, tests/test_objects.py
No functionality was changed, simple removed some redundant stuff like extra parentheses so that it's easier to read.
=> Restructure code so that it's more Pythonic

HISTORY.rst, README.rst, infoblox_client/__init__.py, setup.py
* Bumped version from 0.5.0 to 0.5.1
=> bumped version from 0.5.0 to 0.5.1

README.rst, infoblox_client/connector.py, infoblox_client/objects.py
Reverts infobloxopen/infoblox-client#307
As it breaks backward compatibility of the plugin.
=> Revert "Bug/nios 84275"

infoblox_client/objects.py
* Update operation updates the objects by excluding non-updatable fields
* Added the Logs where non-updatable fields are skipped.
=> Changes to per bug/NIOS-84401

.github/workflows/test.yml, HISTORY.rst, docs/conf.py, docs/index.rst, infoblox_client/connector.py, infoblox_client/objects.py
* Sphinx reported errors while building documentation
* Added auto-generated rst pages to Sphinx exclude_patterns.
* Fixed heading underline for heading 0.5.1 (2022-03-14) in HISTORY.rst
* Created CI job to build documentation and check for Sphinx warnings.
* No tests
=> Fixed minor Sphinx warnings

HISTORY.rst, infoblox_client/connector.py, tests/test_connector.py
* Bumped version from 0.5.0 to 0.5.1
* No Tests
=> Bump version to 0.5.1

infoblox_client/connector.py, tests/test_connector.py
Certificate authentication is not supported.
Added Certificate and Key based authentication.
=> Changes as per Certificate Authentication

HISTORY.rst, README.rst, infoblox_client/__init__.py, setup.py
* Bumped version from 0.5.1 to 0.5.2
=> bump version to 0.5.2

HISTORY.rst, README.rst, infoblox_client/__init__.py, setup.py
* Added support for Python version 3.9 #352;
* Removed support for Python version below 3.0 #352;
=> Bumped version from 0.5.2 to 0.6.0

.github/workflows/test.yml, infoblox_client/connector.py
* The cookie was not preserved/used to when fetching datafile
* simple change to add the persistence of the cookie
* re-tested the script documented in issue #365
=> fixes issue #365
